<?php

namespace Goldcrab\Delma\EquineBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CytologyPFATestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CytologyPFATestRepository extends EntityRepository
{
}
