<?php

namespace Goldcrab\Delma\EquineBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CytologyAFATestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CytologyAFATestRepository extends EntityRepository
{
}
