<?php

namespace Goldcrab\Delma\EquineBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * HorseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HorseRepository extends EntityRepository
{
}
